site_name: Termite Docs
site_url: https://mohammad-h93.github.io/docs-test/

nav:
  - Welcome to Termite: welcome.md
  - Create a Session: sessions.md
  - Integrate Sessions with CAD Software:
      - 'integrate-cad.md'
      - Rhino:
          - Sync: 'sync-rhino.md'
          - Generate: 'generate-rhino.md'
      - Revit:
          - Sync: 'sync-revit.md'
          - Generate: 'generate-revit.md'
      - Grasshopper:
          - Sync: 'sync-grasshopper.md'
          - Generate: 'generate-grasshopper.md'
      - Archicad:
          - Sync: 'sync-archicad.md'
          - Generate: 'generate-archicad.md'
  - Export:
      - dwg: 'export-dwg.md'
      - BIM: 'export-bim.md'


theme:
  font:
    text: Inter
    code: JetBrains Mono
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - stylesheets/extra.css